### ISSUE TITLE
value displayed are not up to date

### ISSUE THREAD

**Issue by ampotos** [vigilate/frontend#67]
On the frontend the value display (like nb of stations) are not up-to-date.

**Comment by eax64** [comment]
With https://github.com/vigilate/frontend/commit/4ffe5f895067afd7296d3d69d5e1bfd9e079e63e value are not kept anymore between a logout and a login.
TODO: When displaying the Dashboard, the dashboard.componen should check if the value have been updated before displaying the numbers.
